"use client";
import { useMemo, useState } from "react";

type Vehicle={brand:string;model:string;version:string;year:number;price:number;km:string;transmission:string;body:string;image:string;tag?:string};
const vehicles:Vehicle[]=[
 {brand:"Volkswagen",model:"T-Cross",version:"Comfortline 1.0 TSI",year:2023,price:109900,km:"42.180 km",transmission:"Automático",body:"SUV",tag:"Oferta",image:"https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=900&q=85"},
 {brand:"Toyota",model:"Corolla",version:"XEi 2.0 Flex",year:2022,price:128900,km:"38.600 km",transmission:"Automático",body:"Sedan",image:"https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=900&q=85"},
 {brand:"Jeep",model:"Compass",version:"Longitude T270",year:2023,price:149900,km:"31.420 km",transmission:"Automático",body:"SUV",tag:"Destaque",image:"https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=900&q=85"},
 {brand:"Chevrolet",model:"Onix",version:"LT 1.0 Turbo",year:2024,price:87900,km:"18.200 km",transmission:"Automático",body:"Hatch",image:"https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=900&q=85"},
 {brand:"Honda",model:"Civic",version:"EXL 2.0",year:2021,price:119900,km:"55.800 km",transmission:"Automático",body:"Sedan",image:"https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=900&q=85"},
 {brand:"Volkswagen",model:"Nivus",version:"Comfortline 200 TSI",year:2023,price:114900,km:"29.140 km",transmission:"Automático",body:"SUV",image:"https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=85"}
];
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0});
const wa=(s:string)=>`https://wa.me/5511961612711?text=${encodeURIComponent(s)}`;

export default function Home(){const [query,setQuery]=useState("");const [body,setBody]=useState("Todos");const filtered=useMemo(()=>vehicles.filter(v=>`${v.brand} ${v.model} ${v.version}`.toLowerCase().includes(query.toLowerCase())&&(body==="Todos"||v.body===body)),[query,body]);return <main>
 <div className="topbar"><span>HME MOTORS</span><span>Seminovos selecionados · procedência e transparência</span><a href="https://maps.app.goo.gl/Efiufs8xijwJaRbt9" target="_blank">Como chegar ↗</a></div>
 <nav className="nav container"><a className="logo" href="#inicio"><i>H</i><span>HME<br/><small>MOTORS</small></span></a><div className="navlinks"><a href="#estoque">Estoque</a><a href="#servicos">Serviços</a><a href="#sobre">A HME</a><a href="#contato">Contato</a></div><a className="nav-whats" href={wa("Olá! Vim pelo site da HME Motors e gostaria de conhecer o estoque.")} target="_blank">Falar com vendedor <b>↗</b></a><button className="menu">☰</button></nav>
 <section className="hero" id="inicio"><div className="hero-bg"/><div className="container hero-content"><p className="eyebrow">SEU PRÓXIMO CARRO ESTÁ AQUI</p><h1>Escolha seu carro.<br/><em>Viva a próxima fase.</em></h1><p className="hero-copy">Carros seminovos revisados, com procedência e condições que cabem no seu momento.</p><div className="hero-actions"><a className="button button-yellow" href="#estoque">Ver estoque <span>↘</span></a><a className="text-link" href={wa("Olá! Quero encontrar um carro ideal para mim.")} target="_blank">Ainda não sabe qual escolher? <u>Fale com a gente</u> ↗</a></div></div><div className="hero-note">Estoque atualizado<br/><strong>toda semana</strong> <span>✦</span></div></section>
 <section className="trust"><div className="container trust-grid"><div><strong>+10 anos</strong><span>realizando escolhas</span></div><div><strong>100%</strong><span>carros revisados</span></div><div><strong>4.9 <small>★</small></strong><span>avaliação no Google</span></div><div><strong>Troca</strong><span>e financiamento</span></div></div></section>
 <section className="stock container" id="estoque"><div className="section-head"><div><p className="eyebrow dark">PRONTO PARA PARTIR</p><h2>Encontre o seu<br/><em>próximo carro.</em></h2></div><a className="outline-button" href="#estoque">Ver todos os carros <span>↗</span></a></div><div className="filters"><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Busque por marca ou modelo"/></label><div className="filter-tabs">{["Todos","SUV","Sedan","Hatch"].map(x=><button key={x} className={body===x?"active":""} onClick={()=>setBody(x)}>{x}</button>)}</div><button className="filter-more">Filtros ☷</button></div><div className="vehicle-grid">{filtered.slice(0,3).map(v=><VehicleCard key={v.model} v={v}/>)}</div>{!filtered.length&&<p className="empty">Nenhum carro encontrado. Fale com um consultor para encontrar o seu.</p>}</section>
 <section className="offer container"><div><p className="eyebrow">CONDIÇÃO ESPECIAL HME</p><h2>Seu carro atual<br/>vale <em>mais aqui.</em></h2><p>Avalie seu usado com quem entende de carro. É rápido, seguro e sem compromisso.</p><a className="button button-dark" href={wa("Olá! Quero avaliar meu carro usado para troca.")} target="_blank">Avaliar meu carro <span>↗</span></a></div><div className="offer-mark">TROCA<br/><strong>JUSTA</strong><br/><small>para você</small></div></section>
 <section className="services" id="servicos"><div className="container"><p className="eyebrow dark">DO SEU JEITO</p><h2>Facilitamos cada<br/><em>parte da escolha.</em></h2><div className="service-grid"><Service n="01" title="Financiamento" text="Condições sob medida para você sair de carro novo." msg="Olá! Quero simular um financiamento."/><Service n="02" title="Visite a loja" text="Venha conhecer seu próximo carro de perto." msg="Olá! Quero agendar uma visita à HME Motors."/><Service n="03" title="Procuro um carro" text="Não encontrou? A gente encontra para você." msg="Olá! Estou procurando um veículo específico."/></div></div></section>
 <section className="location container" id="contato"><div><p className="eyebrow dark">VENHA CONHECER</p><h2>Estamos no<br/><em>seu caminho.</em></h2><p>Av. Sen. Teotônio Vilela, 7041<br/>Jardim São Rafael · São Paulo — SP<br/><strong>Seg a Sex, 9h às 19h · Sáb, 9h às 17h</strong></p><a className="outline-button" href="https://maps.app.goo.gl/Efiufs8xijwJaRbt9" target="_blank">Abrir no Google Maps <span>↗</span></a></div><div className="map-card"><div className="map-lines"/><div className="pin">✦</div><div className="map-label"><strong>HME MOTORS</strong><small>Av. Sen. Teotônio Vilela, 7041</small></div></div></section>
 <footer id="sobre"><div className="container footer-main"><a className="logo light" href="#inicio"><i>H</i><span>HME<br/><small>MOTORS</small></span></a><div><p>O carro certo muda tudo.</p><a href={wa("Olá! Vim pelo site da HME Motors.")} target="_blank" className="footer-whats">WhatsApp <span>↗</span></a></div><div className="footer-address">Av. Sen. Teotônio Vilela, 7041<br/>São Paulo — SP<br/><a href="tel:+5511961612711">+55 11 96161-2711</a></div></div><div className="container footer-bottom"><span>© 2024 HME Motors. Todos os direitos reservados.</span><span>Feito para escolher melhor.</span></div></footer><a className="floating-whats" href={wa("Olá! Vim pelo site da HME Motors e gostaria de falar com um vendedor.")} target="_blank" aria-label="Falar pelo WhatsApp">◔</a>
 </main>}
function VehicleCard({v}:{v:Vehicle}){return <article className="vehicle-card"><div className="vehicle-image"><img src={v.image} alt={`${v.brand} ${v.model}`}/>{v.tag&&<span className="vehicle-tag">{v.tag}</span>}<button aria-label="Favoritar">♡</button></div><div className="vehicle-info"><p className="vehicle-meta">{v.year} <span>·</span> {v.km} <span>·</span> {v.transmission}</p><h3>{v.brand} {v.model}</h3><p className="version">{v.version}</p><div className="vehicle-bottom"><strong>{money(v.price)}</strong><a href={wa(`Olá! Vi o ${v.brand} ${v.model} ${v.version} no site da HME Motors. Ele ainda está disponível?`)} target="_blank">Tenho interesse ↗</a></div></div></article>}
function Service({n,title,text,msg}:{n:string;title:string;text:string;msg:string}){return <a href={wa(msg)} target="_blank"><span>{n}</span><h3>{title}</h3><p>{text}</p><b>Saiba mais ↗</b></a>}
